# Generated by Django 3.1.7 on 2021-03-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210313_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description_long',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, verbose_name='Сокращенное описание'),
        ),
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='place',
            name='title_short',
            field=models.CharField(blank=True, max_length=50, verbose_name='Сокращенное наименование'),
        ),
    ]
