# Generated by Django 3.1.7 on 2021-03-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20210313_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesplace',
            options={'ordering': ['index_number']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='imagesplace',
            name='index_number',
            field=models.PositiveIntegerField(default=0, verbose_name='№ п/п'),
        ),
    ]
